name: Issue triage policies
resource: repository

# See https://eng.ms/docs/more/github-inside-microsoft/policies/fabricbot
configuration:
  fabricBotConfiguration:
    eventResponderTasks:
      # Add Needs Triage label to new issues
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - addLabel:
              label: 'Needs: Triage :mag:'

      # Replace Needs Info label with Needs Triage when the author comments on an issue
      - if:
          - payloadType: Issue_Comment
          - and:
              - isAction:
                  action: Created
              - isActivitySender:
                  user:
                    type: Author
              - hasLabel:
                  label: 'Needs: Information'
              - isOpen:
        then:
          - addLabel:
              label: 'Needs: Triage :mag:'
          - removeLabel:
              label: 'Needs: Information'
