name: Issue lifecycle policies
description: Applies the issue lifecycle policies for labeling, commenting, etc.
resource: repository

# See ./README.md for a cheat sheet
# spell-checker:disable
configuration:
  fabricBotConfiguration:
    eventResponderTasks:
      # 1. #Triage when new issues are created
      # TODO: Consider adding a comment to teach reviewer about what they can do: "@author, thanks for the issue! Please make sure all relevant details are included. @reviewer, please triage this issue. If you need more details, leave a comment with #needs-info..."
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - hasLabel:
                        label: 'Needs: Information'
                    - hasLabel:
                        label: 'Status: ✍️ Spec in progress'
                    - hasLabel:
                        label: 'Status: 🔭 Spec review'
                    - hasLabel:
                        label: 'Status: ▶️ Ready'
                    - hasLabel:
                        label: 'Status: 🔄️ In progress'
                    - hasLabel:
                        label: 'Status: 🔬 Code review'
        then:
          - addLabel:
              label: 'Needs: Triage 🔍'
          - assignTo:
              user: flanakin
