name: Issue needs triage
description: Add Needs Triage label to new issues
resource: repository

# See https://eng.ms/docs/more/github-inside-microsoft/policies/fabricbot
configuration:
  fabricBotConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Issues
          - and:
              - isOpen
              - not:
                  and:
                    - isAssignedToSomeone
                    - isLabeled
        then:
          - addLabel:
              label: 'Needs: Triage :mag:'
