name: Issue lifecycle policies
description: Applies the issue lifecycle policies for labeling, commenting, etc.
resource: repository

# See ./README.md for a cheat sheet
# spell-checker:disable
configuration:
  fabricBotConfiguration:
    - scheduledSearches:
        # 2a1. +#Attention when no activity
        - frequencies:
            - daily:
                time: 01:00
          searchTerms:
            - isIssue
            - isOpen
            - hasLabel:
                label: 'Needs: Information'
            - not:
                - hasLabel:
                    label: 'Needs: Attention 👋'
            - noActivitySince:
                days: 14
          actions:
            - addLabel:
                label: 'Needs: Attention 👋'
            - addReply: # spell-checker:enable
                reply: "Hey, there! 👋 Looks like you haven't checked in for a while. (14 days, but who's counting? )<br><br>We need a bit more information in order to address the feedback. Please take a moment to share the requested details or let us know if you need clarification and we'll check back in later."
                # spell-checker:disable

        # 2a2. #Attention > Close when no activity
        - frequencies:
            - daily:
                time: 01:00
          searchTerms:
            - isIssue
            - isOpen
            - hasLabel:
                label: 'Needs: Information'
            - hasLabel:
                label: 'Needs: Attention 👋'
            - noActivitySince:
                days: 14
          actions:
            - closeIssue
            - addLabel:
                label: 'Resolution: No activity'
            - addReply: # spell-checker:enable
                reply: "Well, here we are again... It's been a month since we last saw you. (Okay, 28 days.) We weren't able to get the details we need to take the next steps, so we're going to close this issue for now. Please create a new issue with the extra details if you'd like us to consider this for a future release. Thanks!"
                # spell-checker:disable

        # 2b1. #Duplicate > Close when no activity
        - frequencies:
            - daily:
                time: 01:00
          searchTerms:
            - isIssue
            - isOpen
            - hasLabel:
                label: 'Resolution: Duplicate'
            - noActivitySince:
                days: 7
          actions:
            - closeIssue
            - addReply: # spell-checker:enable
                reply: "We noticed this issue was flagged as a duplicate over a week ago. Since we haven't heard from anyone, we're going to close it. Please file a new issue if you believe this is a unique issue and not a duplicate."
                # spell-checker:disable


