name: PR needs review
description: Assign Needs Review label to new/updated PRs
resource: repository

# See ./README.md for a cheat sheet
# spell-checker:disable
configuration:
  fabricBotConfiguration:
    eventResponderTasks:
      - if:
          - payloadType: Pull_Request
          - and:
              - targetsBranch:
                  branch: main
              - isOpen
              - or:
                  - isAction:
                      action: Requested
                  - isAction:
                      action: Synchronize
        then:
          - addLabel:
              label: 'Needs: Review 👀'
