id: pulls-02-feedback
name: GitOps.PullRequestIssueManagement
description: Handles when a PR gets feedback
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: >-
          When a PR gets feedback:
          - Assign to author
          - Label with `Needs: Attention 👋`
        if:
          - or:
              - payloadType: Pull_Request_Review_Comment
              - and:
                  - payloadType: Pull_Request_Review
                  - isReviewState:
                      reviewState: Changes_requested
          - not:
              targetsBranch:
                branch: main
        then:
          - addLabel:
              label: 'Needs: Attention 👋'
          - assignTo:
              author: True
onFailure:
onSuccess:
