id: pulls-00-file-paths
name: GitOps.PullRequestIssueManagement
description: Handles when a PR is opened with specific file paths
owner:
resource: repository
disabled: false
where:

# spell-checker:disable
configuration:
  resourceManagementConfiguration:
    eventResponderTasks:
      - description: When a PR is opened, add labels based on file paths
        if:
          - payloadType: Pull_Request
          - isAction:
              action: Opened
          - not:
              targetsBranch:
                branch: main
        then:
          # GitHub
          - if:
              - filesMatchPattern:
                  pattern: ^.github/.*
            then:
              - addLabel:
                  label: 'Area: DevOps'
              - if:
                  - not:
                      isAssignedToUser:
                        user: aromano2
                then:
                  - requestReview:
                      reviewer: aromano2
              - if:
                  - not:
                      isAssignedToUser:
                        user: flanakin
                then:
                  - requestReview:
                      reviewer: flanakin
          # docs
          - if:
              - filesMatchPattern:
                  pattern: ^docs/.*
            then:
              - addLabel:
                  label: 'Area: Documentation'
              - if:
                  - not:
                      isAssignedToUser:
                        user: flanakin
                then:
                  - requestReview:
                      reviewer: flanakin
          # bicep
          - if:
              - filesMatchPattern:
                  pattern: ^(docs|src)/bicep-registry/.*
            then:
              - addLabel:
                  label: 'Solution: Bicep Registry'
              - if:
                  - not:
                      isAssignedToUser:
                        user: flanakin
                then:
                  - requestReview:
                      reviewer: flanakin
          # hubs
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^docs/finops-hub/.*
                  - filesMatchPattern:
                      pattern: ^src/templates/finops-hub/.*
                  - filesMatchPattern:
                      pattern: ^src/powershell/(Public|Private)/[^-]+-FinOpsHub[^\.]*\.ps1
            then:
              - addLabel:
                  label: 'Solution: FinOps hubs'
              - if:
                  - not:
                      isAssignedToUser:
                        user: flanakin
                then:
                  - requestReview:
                      reviewer: flanakin
              - if:
                  - not:
                      isAssignedToUser:
                        user: msbrett
                then:
                  - requestReview:
                      reviewer: msbrett
          # powershell
          - if:
              - filesMatchPattern:
                  pattern: ^(docs|src)/powershell/.*
            then:
              - addLabel:
                  label: 'Area: PowerShell'
              - if:
                  - not:
                      isAssignedToUser:
                        user: aromano2
                then:
                  - requestReview:
                      reviewer: aromano2
              - if:
                  - not:
                      isAssignedToUser:
                        user: arthurclares
                then:
                  - requestReview:
                      reviewer: arthurclares
              - if:
                  - not:
                      isAssignedToUser:
                        user: didayal-msft
                then:
                  - requestReview:
                      reviewer: didayal-msft
              - if:
                  - not:
                      isAssignedToUser:
                        user: flanakin
                then:
                  - requestReview:
                      reviewer: flanakin
              - if:
                  - not:
                      isAssignedToUser:
                        user: saadmsft
                then:
                  - requestReview:
                      reviewer: saadmsft
              - if:
                  - not:
                      isAssignedToUser:
                        user: sebassem
                then:
                  - requestReview:
                      reviewer: sebassem
              - if:
                  - not:
                      isAssignedToUser:
                        user: springstone
                then:
                  - requestReview:
                      reviewer: springstone
          # workbooks
          - if:
              - or:
                  - filesMatchPattern:
                      pattern: ^docs/[^-]+-workbook/.*
                  - filesMatchPattern:
                      pattern: ^src/workbooks/.*
            then:
              - addLabel:
                  label: 'Solution: Workbooks'
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^docs/optimization-workbook/.*
                      - filesMatchPattern:
                          pattern: ^src/workbooks/optimization/.*
                  - not:
                      isAssignedToUser:
                        user: arthurclares
                then:
                  - requestReview:
                      reviewer: arthurclares
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^docs/governance-workbook/.*
                      - filesMatchPattern:
                          pattern: ^src/workbooks/governance/.*
                  - not:
                      isAssignedToUser:
                        user: nteyan
                then:
                  - requestReview:
                      reviewer: nteyan
              - if:
                  - not:
                      isAssignedToUser:
                        user: flanakin
                then:
                  - requestReview:
                      reviewer: flanakin
              - if:
                  - or:
                      - filesMatchPattern:
                          pattern: ^docs/optimization-workbook/.*
                      - filesMatchPattern:
                          pattern: ^src/workbooks/optimization/.*
                  - not:
                      isAssignedToUser:
                        user: sebassem
                then:
                  - requestReview:
                      reviewer: sebassem
onFailure:
onSuccess:
