title: FinOps toolkit
description: A collection of customizable FinOps solutions that automate and extend native Microsoft Cloud capabilities.
remote_theme: just-the-docs/just-the-docs

url: https://microsoft.github.io/finops-toolkit

aux_links:
  FTK on GitHub: https://github.com/microsoft/finops-toolkit
