name: 'Unit Tests'

on: [pull_request]
jobs:
    run_pester_tests:
        name: Run Unit Tests
        runs-on: Windows-latest
        steps:
        - uses: actions/checkout@v3
        - name: Pester
          shell: pwsh
          run: ./src/scripts/Start-PesterTests.ps1
            